export const sports = [
  { id: "1", name: "Basketball", icon: "basketball" },
  { id: "2", name: "Soccer", icon: "soccer" },
  { id: "3", name: "Tennis", icon: "tennis" },
  { id: "4", name: "Swimming", icon: "swimming" },
  { id: "5", name: "Running", icon: "running" },
  { id: "6", name: "Volleyball", icon: "volleyball" },
  { id: "7", name: "Boxing", icon: "boxing" },
  { id: "8", name: "Yoga", icon: "yoga" },
  { id: "9", name: "Cycling", icon: "cycling" },
  { id: "10", name: "Golf", icon: "golf" },
]

export const activities = [
  {
    id: "1",
    title: "5v5 Basketball Pickup Game",
    sport: "Basketball",
    date: "Feb 10, 2026",
    time: "6:00 PM - 8:00 PM",
    location: "Chelsea Piers, NYC",
    price: 15,
    currency: "$",
    spots: 3,
    totalSpots: 10,
    image: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&h=250&fit=crop",
    rating: 4.8,
    reviews: 24,
    organizer: "Mike Johnson",
    organizerAvatar: "MJ",
    tags: ["Competitive", "Indoor"],
    description: "Join our weekly 5v5 basketball game at Chelsea Piers. All skill levels welcome but competitive play expected.",
  },
  {
    id: "2",
    title: "Morning Beach Volleyball",
    sport: "Volleyball",
    date: "Feb 11, 2026",
    time: "8:00 AM - 10:00 AM",
    location: "Rockaway Beach, NYC",
    price: 0,
    currency: "$",
    spots: 6,
    totalSpots: 12,
    image: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=400&h=250&fit=crop",
    rating: 4.6,
    reviews: 18,
    organizer: "Sarah Lee",
    organizerAvatar: "SL",
    tags: ["Casual", "Outdoor"],
    description: "Friendly beach volleyball on Saturday mornings. Bring your own water and sunscreen!",
  },
  {
    id: "3",
    title: "Tennis Doubles Match",
    sport: "Tennis",
    date: "Feb 12, 2026",
    time: "4:00 PM - 6:00 PM",
    location: "Central Park Courts, NYC",
    price: 25,
    currency: "$",
    spots: 1,
    totalSpots: 4,
    image: "https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=400&h=250&fit=crop",
    rating: 4.9,
    reviews: 32,
    organizer: "Alex Chen",
    organizerAvatar: "AC",
    tags: ["Intermediate", "Outdoor"],
    description: "Looking for a 4th player for doubles. Intermediate level preferred.",
  },
  {
    id: "4",
    title: "Group Swimming Laps",
    sport: "Swimming",
    date: "Feb 13, 2026",
    time: "7:00 AM - 8:30 AM",
    location: "Asphalt Green, NYC",
    price: 20,
    currency: "$",
    spots: 5,
    totalSpots: 8,
    image: "https://images.unsplash.com/photo-1530549387789-4c1017266635?w=400&h=250&fit=crop",
    rating: 4.7,
    reviews: 15,
    organizer: "Emily Park",
    organizerAvatar: "EP",
    tags: ["Fitness", "Indoor"],
    description: "Structured swimming workout with coached drills. Bring your own goggles.",
  },
  {
    id: "5",
    title: "Sunday Soccer League",
    sport: "Soccer",
    date: "Feb 15, 2026",
    time: "10:00 AM - 12:00 PM",
    location: "Randalls Island, NYC",
    price: 10,
    currency: "$",
    spots: 8,
    totalSpots: 22,
    image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400&h=250&fit=crop",
    rating: 4.5,
    reviews: 45,
    organizer: "Carlos Rivera",
    organizerAvatar: "CR",
    tags: ["League", "Outdoor"],
    description: "Weekly 11v11 soccer league. Season runs Feb-May. All skill levels welcome.",
  },
  {
    id: "6",
    title: "Boxing Fundamentals Class",
    sport: "Boxing",
    date: "Feb 14, 2026",
    time: "5:30 PM - 7:00 PM",
    location: "Gleason's Gym, Brooklyn",
    price: 30,
    currency: "$",
    spots: 4,
    totalSpots: 12,
    image: "https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=400&h=250&fit=crop",
    rating: 4.9,
    reviews: 52,
    organizer: "James Wright",
    organizerAvatar: "JW",
    tags: ["Beginner", "Indoor"],
    description: "Learn boxing basics with a certified trainer. Gloves provided.",
  },
]

export const facilities = [
  {
    id: "1",
    name: "Chelsea Piers Sports Center",
    type: "Multi-Sport Complex",
    location: "62 Chelsea Piers, NYC",
    coordinates: [40.7465, -74.0071],
    rating: 4.8,
    reviews: 156,
    pricePerHour: 45,
    currency: "$",
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=250&fit=crop",
    amenities: ["Parking", "Lockers", "Showers", "Pro Shop", "Cafe"],
    hours: "6:00 AM - 11:00 PM",
    sports: ["Basketball", "Swimming", "Tennis", "Volleyball"],
    available: true,
    capacity: 80,
    description: "Multi-sport complex with courts, pools, and training facilities under one roof.",
  },
  {
    id: "2",
    name: "Brooklyn Bridge Park Courts",
    type: "Outdoor Courts",
    location: "334 Furman St, Brooklyn",
    coordinates: [40.7025, -73.9967],
    rating: 4.5,
    reviews: 89,
    pricePerHour: 0,
    currency: "$",
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=250&fit=crop",
    amenities: ["Free Entry", "Water Fountain", "Restrooms"],
    hours: "6:00 AM - 10:00 PM",
    sports: ["Basketball", "Soccer", "Volleyball"],
    available: true,
    capacity: 50,
    description: "Outdoor courts with skyline views and community pickup games.",
  },
  {
    id: "3",
    name: "USTA Billie Jean King Center",
    type: "Tennis Center",
    location: "Flushing Meadows, Queens",
    coordinates: [40.7498, -73.8476],
    rating: 4.9,
    reviews: 210,
    pricePerHour: 65,
    currency: "$",
    image: "https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=400&h=250&fit=crop",
    amenities: ["Parking", "Lockers", "Pro Shop", "Restaurant", "Training"],
    hours: "7:00 AM - 10:00 PM",
    sports: ["Tennis"],
    available: true,
    capacity: 30,
    description: "Premier tennis center with pro coaching and tournament-grade courts.",
  },
  {
    id: "4",
    name: "Asphalt Green Aquatics",
    type: "Swimming Center",
    location: "555 E 90th St, NYC",
    coordinates: [40.7828, -73.9442],
    rating: 4.7,
    reviews: 134,
    pricePerHour: 35,
    currency: "$",
    image: "https://images.unsplash.com/photo-1576610616656-d3aa5d1f4534?w=400&h=250&fit=crop",
    amenities: ["Olympic Pool", "Lockers", "Sauna", "Training"],
    hours: "5:30 AM - 9:30 PM",
    sports: ["Swimming"],
    available: false,
    capacity: 60,
    description: "Aquatics center with Olympic pool and recovery amenities.",
  },
]

export const products = [
  {
    id: "1",
    name: "Pro Basketball Shoes",
    brand: "Nike",
    price: 149.99,
    originalPrice: 179.99,
    currency: "$",
    rating: 4.7,
    reviews: 89,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=250&fit=crop",
    category: "Footwear",
    inStock: true,
    seller: "SportGear NYC",
    description: "Lightweight basketball shoes designed for speed, grip, and all-court stability.",
  },
  {
    id: "2",
    name: "Carbon Tennis Racket",
    brand: "Wilson",
    price: 219.99,
    originalPrice: 249.99,
    currency: "$",
    rating: 4.9,
    reviews: 45,
    image: "https://images.unsplash.com/photo-1617883861744-13b534e1396b?w=400&h=250&fit=crop",
    category: "Equipment",
    inStock: true,
    seller: "Tennis Pro Shop",
    description: "Carbon fiber racket tuned for power and precision with a comfortable grip.",
  },
  {
    id: "3",
    name: "Compression Training Set",
    brand: "Under Armour",
    price: 89.99,
    currency: "$",
    rating: 4.5,
    reviews: 120,
    image: "https://images.unsplash.com/photo-1556906781-9a412961c28c?w=400&h=250&fit=crop",
    category: "Apparel",
    inStock: true,
    seller: "FitWear Store",
    description: "Moisture-wicking compression set for high-intensity training days.",
  },
  {
    id: "4",
    name: "Smart Fitness Watch",
    brand: "Garmin",
    price: 299.99,
    originalPrice: 349.99,
    currency: "$",
    rating: 4.8,
    reviews: 200,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=250&fit=crop",
    category: "Wearables",
    inStock: true,
    seller: "TechSport NYC",
    description: "Advanced GPS watch with heart-rate tracking and recovery insights.",
  },
  {
    id: "5",
    name: "Yoga Mat Premium",
    brand: "Manduka",
    price: 78.00,
    currency: "$",
    rating: 4.6,
    reviews: 67,
    image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&h=250&fit=crop",
    category: "Equipment",
    inStock: true,
    seller: "Zen Sports",
    description: "Dense, supportive yoga mat with non-slip grip and long-lasting durability.",
  },
  {
    id: "6",
    name: "Swimming Goggles Elite",
    brand: "Speedo",
    price: 42.00,
    currency: "$",
    rating: 4.4,
    reviews: 55,
    image: "https://images.unsplash.com/photo-1572631382901-cf38e0e23685?w=400&h=250&fit=crop",
    category: "Equipment",
    inStock: false,
    seller: "AquaGear",
    description: "Low-profile goggles with anti-fog coating and leak-free seal.",
  },
]

export const services = [
  {
    id: "1",
    name: "Personal Basketball Training",
    provider: "Coach Mike Johnson",
    providerAvatar: "MJ",
    duration: "60 min",
    price: 85,
    currency: "$",
    rating: 4.9,
    reviews: 67,
    image: "https://images.unsplash.com/photo-1519861531473-9200262188bf?w=400&h=250&fit=crop",
    category: "Training",
    verified: true,
    description: "One-on-one basketball skills training. Shooting, dribbling, and game IQ.",
  },
  {
    id: "2",
    name: "Sports Massage Therapy",
    provider: "NYC Sports Recovery",
    providerAvatar: "SR",
    duration: "90 min",
    price: 120,
    currency: "$",
    rating: 4.8,
    reviews: 94,
    image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400&h=250&fit=crop",
    category: "Recovery",
    verified: true,
    description: "Deep tissue massage targeting sports-related tension and recovery.",
  },
  {
    id: "3",
    name: "Group Yoga Sessions",
    provider: "Zen Athletics",
    providerAvatar: "ZA",
    duration: "75 min",
    price: 25,
    currency: "$",
    rating: 4.7,
    reviews: 156,
    image: "https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=400&h=250&fit=crop",
    category: "Wellness",
    verified: true,
    description: "Group yoga sessions tailored for athletes. Focus on flexibility and mindfulness.",
  },
  {
    id: "4",
    name: "Running Coach Program",
    provider: "NYC Run Club",
    providerAvatar: "RC",
    duration: "8 weeks",
    price: 200,
    currency: "$",
    rating: 4.6,
    reviews: 42,
    image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400&h=250&fit=crop",
    category: "Training",
    verified: false,
    description: "8-week structured running program from 5K to half marathon.",
  },
]

export const businesses = [
  {
    id: "1",
    name: "Chelsea Piers Sports",
    type: "Sports Complex",
    location: "Chelsea, NYC",
    rating: 4.8,
    reviews: 312,
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=250&fit=crop",
    followers: 2450,
    activities: 24,
    verified: true,
  },
  {
    id: "2",
    name: "Brooklyn Fitness Hub",
    type: "Gym & Training",
    location: "Williamsburg, Brooklyn",
    rating: 4.6,
    reviews: 187,
    image: "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=400&h=250&fit=crop",
    followers: 1830,
    activities: 18,
    verified: true,
  },
  {
    id: "3",
    name: "Manhattan Tennis Club",
    type: "Tennis Academy",
    location: "Midtown, NYC",
    rating: 4.9,
    reviews: 98,
    image: "https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=400&h=250&fit=crop",
    followers: 920,
    activities: 12,
    verified: true,
  },
  {
    id: "4",
    name: "Wave Runners Swim",
    type: "Aquatics Center",
    location: "Upper East Side, NYC",
    rating: 4.7,
    reviews: 145,
    image: "https://images.unsplash.com/photo-1576610616656-d3aa5d1f4534?w=400&h=250&fit=crop",
    followers: 680,
    activities: 8,
    verified: false,
  },
]

export const jobs = [
  {
    id: "1",
    title: "Head Basketball Coach",
    company: "Chelsea Piers Sports",
    location: "Chelsea, NYC",
    type: "Full-time",
    salary: "$60K - $80K",
    posted: "2 days ago",
    description: "Lead basketball coaching programs for youth and adult leagues.",
    requirements: ["5+ years coaching experience", "NAIA or NCAA certification", "Strong communication skills"],
    logo: "CP",
  },
  {
    id: "2",
    title: "Fitness Trainer",
    company: "Brooklyn Fitness Hub",
    location: "Williamsburg, Brooklyn",
    type: "Part-time",
    salary: "$30 - $50/hr",
    posted: "1 day ago",
    description: "Provide personal training sessions and group fitness classes.",
    requirements: ["ACE or NASM certified", "2+ years experience", "CPR certified"],
    logo: "BF",
  },
  {
    id: "3",
    title: "Tennis Instructor",
    company: "Manhattan Tennis Club",
    location: "Midtown, NYC",
    type: "Full-time",
    salary: "$45K - $65K",
    posted: "3 days ago",
    description: "Teach tennis fundamentals and advanced techniques to all age groups.",
    requirements: ["USPTA certification", "Playing experience", "Bilingual preferred"],
    logo: "MT",
  },
  {
    id: "4",
    title: "Swim Team Coordinator",
    company: "Wave Runners Swim",
    location: "Upper East Side, NYC",
    type: "Full-time",
    salary: "$50K - $70K",
    posted: "5 days ago",
    description: "Coordinate swim team schedules, events, and training programs.",
    requirements: ["Lifeguard certified", "Event planning experience", "Swim coaching background"],
    logo: "WR",
  },
  {
    id: "5",
    title: "Sports Event Manager",
    company: "Chelsea Piers Sports",
    location: "Chelsea, NYC",
    type: "Contract",
    salary: "$55K - $75K",
    posted: "1 week ago",
    description: "Plan and execute sports events, tournaments, and community activities.",
    requirements: ["Event management experience", "Strong organizational skills", "Sports industry knowledge"],
    logo: "CP",
  },
]

export const businessResources = [
  { id: "1", name: "Basketball Court A", type: "Court", status: "available", bookingsToday: 5, revenue: 225, image: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=200&h=200&fit=crop" },
  { id: "2", name: "Tennis Court 1", type: "Court", status: "occupied", bookingsToday: 3, revenue: 195, image: "https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=200&h=200&fit=crop" },
  { id: "3", name: "Olympic Pool", type: "Pool", status: "available", bookingsToday: 8, revenue: 280, image: "https://images.unsplash.com/photo-1576610616656-d3aa5d1f4534?w=200&h=200&fit=crop" },
  { id: "4", name: "Yoga Studio B", type: "Studio", status: "maintenance", bookingsToday: 0, revenue: 0, image: "https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=200&h=200&fit=crop" },
  { id: "5", name: "Boxing Ring", type: "Ring", status: "available", bookingsToday: 4, revenue: 320, image: "https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=200&h=200&fit=crop" },
]

export const businessPartners = [
  { id: "1", name: "LeBron Athletics", type: "Sponsor", tier: "Gold", contribution: 5000, avatar: "LA", since: "Jan 2025" },
  { id: "2", name: "Sarah Lee", type: "Athlete", sport: "Volleyball", ranking: "#12 NYC", avatar: "SL", since: "Mar 2025" },
  { id: "3", name: "Nike NYC", type: "Sponsor", tier: "Platinum", contribution: 15000, avatar: "NK", since: "Nov 2024" },
  { id: "4", name: "Carlos Rivera", type: "Athlete", sport: "Soccer", ranking: "#5 NYC", avatar: "CR", since: "Feb 2025" },
  { id: "5", name: "Gatorade", type: "Sponsor", tier: "Silver", contribution: 2500, avatar: "GA", since: "Jun 2025" },
  { id: "6", name: "Mike Johnson", type: "Athlete", sport: "Basketball", ranking: "#3 NYC", avatar: "MJ", since: "Jan 2025" },
]

export const goals = [
  {
    id: "1",
    title: "Run 100 Miles",
    progress: 67,
    target: 100,
    unit: "miles",
    deadline: "Mar 31, 2026",
    sport: "Running",
    milestones: [
      { id: "m1", title: "Run 10 miles without stopping", completed: true },
      { id: "m2", title: "Complete 5 interval training sessions", completed: true },
      { id: "m3", title: "Run a half-marathon distance", completed: false },
    ],
  },
  {
    id: "2",
    title: "Attend 20 Basketball Games",
    progress: 12,
    target: 20,
    unit: "games",
    deadline: "Jun 30, 2026",
    sport: "Basketball",
    milestones: [
      { id: "m1", title: "Join 5 pickup games", completed: true },
      { id: "m2", title: "Play in a league match", completed: true },
      { id: "m3", title: "Complete a tournament", completed: false },
    ],
  },
  {
    id: "3",
    title: "Swim 50 Laps Weekly",
    progress: 35,
    target: 50,
    unit: "laps",
    deadline: "Weekly",
    sport: "Swimming",
    milestones: [
      { id: "m1", title: "Swim 20 laps without rest", completed: true },
      { id: "m2", title: "Improve 100m time by 10%", completed: false },
      { id: "m3", title: "Complete 50 laps in one session", completed: false },
    ],
  },
]

export const notifications = [
  {
    id: "1",
    type: "activity",
    title: "Activity Reminder",
    message: "5v5 Basketball Pickup Game starts in 2 hours",
    time: "2 hours ago",
    read: false,
  },
  {
    id: "2",
    type: "social",
    title: "New Follower",
    message: "Sarah Lee started following you",
    time: "4 hours ago",
    read: false,
  },
  {
    id: "3",
    type: "booking",
    title: "Booking Confirmed",
    message: "Your court booking at Chelsea Piers is confirmed for Feb 10",
    time: "1 day ago",
    read: true,
  },
  {
    id: "4",
    type: "achievement",
    title: "Achievement Unlocked",
    message: "You earned the 'Early Bird' badge for 10 morning activities!",
    time: "2 days ago",
    read: true,
  },
  {
    id: "5",
    type: "system",
    title: "System Update",
    message: "New features available! Check out the updated marketplace.",
    time: "3 days ago",
    read: true,
  },
]

export const conversations = [
  {
    id: "1",
    name: "Mike Johnson",
    avatar: "MJ",
    lastMessage: "See you at the game tonight!",
    time: "2m ago",
    timestamp: "2026-02-08T11:58:00",
    unread: 2,
    online: true,
  },
  {
    id: "2",
    name: "Sarah Lee",
    avatar: "SL",
    lastMessage: "Thanks for the invite! I'll be there.",
    time: "15m ago",
    timestamp: "2026-02-08T11:45:00",
    unread: 0,
    online: true,
  },
  {
    id: "3",
    name: "Chelsea Piers Sports",
    avatar: "CP",
    lastMessage: "Your booking has been confirmed.",
    time: "1h ago",
    timestamp: "2026-02-08T11:00:00",
    unread: 1,
    online: false,
  },
  {
    id: "4",
    name: "Alex Chen",
    avatar: "AC",
    lastMessage: "Great match yesterday!",
    time: "3h ago",
    timestamp: "2026-02-08T09:00:00",
    unread: 0,
    online: false,
  },
  {
    id: "5",
    name: "NYC Run Club",
    avatar: "RC",
    lastMessage: "Next group run is on Saturday at 7 AM",
    time: "1d ago",
    timestamp: "2026-02-07T12:00:00",
    unread: 0,
    online: false,
  },
]

export const organizerPortfolioEvents = [
  {
    id: "1",
    name: "Summer Basketball Championship 2025",
    date: "2025-06-15",
    location: "Downtown Sports Arena",
    metrics: {
      attendance: 2500,
      mediaReach: 150000,
      engagementRate: 12.5,
      geographicReach: ["New York", "New Jersey", "Connecticut"],
    },
    proof: {
      photos: ["event1-photo1.jpg", "event1-photo2.jpg", "event1-photo3.jpg"],
      mediaLinks: ["https://localnews.com/basketball-championship", "https://sportsdaily.com/summer-event"],
      socialMediaLinks: ["https://instagram.com/post1", "https://twitter.com/post1"],
      documents: ["attendance-report.pdf", "event-summary.pdf"],
    },
    testimonials: [
      {
        author: "Nike NYC",
        role: "Event Sponsor",
        text: "Exceptional event organization and impressive turnout. The engagement metrics exceeded expectations.",
      },
    ],
  },
  {
    id: "2",
    name: "Youth Soccer League - Spring Season",
    date: "2025-04-20",
    location: "Central Park Fields",
    metrics: {
      attendance: 1800,
      mediaReach: 85000,
      engagementRate: 15.2,
      geographicReach: ["Manhattan", "Brooklyn", "Queens"],
    },
    proof: {
      photos: ["event2-photo1.jpg", "event2-photo2.jpg"],
      mediaLinks: ["https://nycsports.com/youth-soccer"],
      socialMediaLinks: ["https://facebook.com/post1"],
      documents: ["league-results.pdf"],
    },
    testimonials: [
      {
        author: "Adidas Youth Sports",
        role: "Title Sponsor",
        text: "Well-organized league with strong community engagement. Great partnership opportunity.",
      },
    ],
  },
]

export const userProfile = {
  name: "Jordan Rivera",
  username: "@jordanr",
  avatar: "JR",
  bio: "Sports enthusiast | Basketball & Tennis | NYC",
  location: "New York City",
  memberSince: "Jan 2025",
  followers: 234,
  following: 156,
  activitiesJoined: 48,
  badges: [
    { name: "Early Bird", icon: "sunrise" },
    { name: "Team Player", icon: "users" },
    { name: "Marathon Runner", icon: "medal" },
    { name: "Social Butterfly", icon: "heart" },
  ],
  stats: {
    totalActivities: 48,
    hoursPlayed: 156,
    sportsPlayed: 5,
    avgRating: 4.8,
  },
  favoriteSports: ["Basketball", "Tennis", "Running"],
  walletBalance: 125.5,
}

export const posts = [
  {
    id: "1",
    author: "Mike Johnson",
    authorAvatar: "MJ",
    time: "2 hours ago",
    content: "Just finished an amazing 5v5 basketball session at Chelsea Piers! The energy was incredible tonight. Who's joining next week?",
    image: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=600&h=400&fit=crop",
    likes: 42,
    comments: 8,
    shares: 3,
    sport: "Basketball",
  },
  {
    id: "2",
    author: "Sarah Lee",
    authorAvatar: "SL",
    time: "4 hours ago",
    content: "Beautiful morning for beach volleyball at Rockaway! Nothing beats starting your day with sand between your toes and a great game. See you all next Saturday!",
    image: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=600&h=400&fit=crop",
    likes: 67,
    comments: 12,
    shares: 5,
    sport: "Volleyball",
  },
  {
    id: "3",
    author: "NYC Run Club",
    authorAvatar: "RC",
    time: "6 hours ago",
    content: "Registration is now open for our Spring 10K race through Central Park! Early bird pricing available until March 1st. Limited spots available.",
    likes: 128,
    comments: 34,
    shares: 22,
    sport: "Running",
  },
  {
    id: "4",
    author: "Alex Chen",
    authorAvatar: "AC",
    time: "1 day ago",
    content: "New personal best on my tennis serve today - 112 mph! Months of training finally paying off. Thanks to Coach Rivera for the technique adjustments.",
    likes: 89,
    comments: 15,
    shares: 7,
    sport: "Tennis",
  },
  {
    id: "5",
    author: "Chelsea Piers Sports",
    authorAvatar: "CP",
    time: "1 day ago",
    content: "Exciting news! We just upgraded our swimming pool facilities with Olympic-grade timing systems. Book your lane today and experience the difference.",
    image: "https://images.unsplash.com/photo-1576610616656-d3aa5d1f4534?w=600&h=400&fit=crop",
    likes: 203,
    comments: 28,
    shares: 45,
    sport: "Swimming",
  },
]

export const transactionHistory = [
  { id: "T001", type: "payment", description: "Basketball Court Booking", amount: -45, date: "Feb 7, 2026", status: "completed" },
  { id: "T002", type: "deposit", description: "Wallet Top Up", amount: 100, date: "Feb 5, 2026", status: "completed" },
  { id: "T003", type: "payment", description: "Tennis Racket - Wilson", amount: -219.99, date: "Feb 3, 2026", status: "completed" },
  { id: "T004", type: "refund", description: "Cancelled Yoga Session", amount: 25, date: "Feb 1, 2026", status: "completed" },
  { id: "T005", type: "payment", description: "Swimming Laps - Asphalt Green", amount: -20, date: "Jan 30, 2026", status: "completed" },
  { id: "T006", type: "payment", description: "Personal Training Session", amount: -85, date: "Jan 28, 2026", status: "pending" },
  { id: "T007", type: "deposit", description: "Wallet Top Up", amount: 200, date: "Jan 25, 2026", status: "completed" },
  { id: "T008", type: "payment", description: "Sports Massage Therapy", amount: -120, date: "Jan 22, 2026", status: "completed" },
]

export const paymentMethods = [
  { id: "1", type: "visa", last4: "4242", expiry: "12/27", isDefault: true },
  { id: "2", type: "mastercard", last4: "8888", expiry: "09/28", isDefault: false },
  { id: "3", type: "paypal", email: "jordan@email.com", isDefault: false },
]

export const experienceLevels = [
  { id: "beginner", label: "Beginner", description: "Just getting started with sports and fitness" },
  { id: "intermediate", label: "Intermediate", description: "Comfortable with regular training and games" },
  { id: "advanced", label: "Advanced", description: "Competitive level with years of experience" },
]

export const people = [
  { id: "1", name: "Mike Johnson", sport: "Basketball", role: "Athlete", location: "NYC", followers: 1250, rating: 4.9, avatar: "MJ", verified: true, bio: "Professional basketball player and youth coach" },
  { id: "2", name: "Sarah Lee", sport: "Volleyball", role: "Athlete", location: "Brooklyn", followers: 890, rating: 4.7, avatar: "SL", verified: true, bio: "Beach volleyball champion and fitness influencer" },
  { id: "3", name: "Alex Chen", sport: "Tennis", role: "Coach", location: "Manhattan", followers: 2100, rating: 4.8, avatar: "AC", verified: true, bio: "ATP-ranked tennis player turned elite coach" },
  { id: "4", name: "Carlos Rivera", sport: "Soccer", role: "Athlete", location: "Queens", followers: 3400, rating: 4.6, avatar: "CR", verified: false, bio: "Semi-pro soccer player and sports content creator" },
  { id: "5", name: "Emily Park", sport: "Swimming", role: "Influencer", location: "NYC", followers: 5600, rating: 4.9, avatar: "EP", verified: true, bio: "Olympic trial swimmer and wellness advocate" },
  { id: "6", name: "James Wright", sport: "Boxing", role: "Coach", location: "Brooklyn", followers: 780, rating: 4.8, avatar: "JW", verified: false, bio: "Former amateur boxing champion and certified trainer" },
]

export const squads = [
  {
    id: "1",
    name: "NYC Hoops Crew",
    sport: "Basketball",
    members: 12,
    maxMembers: 15,
    avatar: "NH",
    description: "Weekly pickup basketball games across NYC courts",
    upcomingEvents: 3,
    wins: 24,
    losses: 8,
    captain: "Mike Johnson",
    captainAvatar: "MJ",
    recentActivity: "Won against Brooklyn Ballers 78-65",
    memberList: [
      { name: "Mike Johnson", role: "Captain", avatar: "MJ" },
      { name: "Jordan Rivera", role: "Member", avatar: "JR" },
      { name: "David Kim", role: "Member", avatar: "DK" },
      { name: "Mark Brown", role: "Member", avatar: "MB" },
    ],
  },
  {
    id: "2",
    name: "Tennis Aces NYC",
    sport: "Tennis",
    members: 8,
    maxMembers: 10,
    avatar: "TA",
    description: "Competitive doubles and singles matches every weekend",
    upcomingEvents: 2,
    wins: 15,
    losses: 5,
    captain: "Alex Chen",
    captainAvatar: "AC",
    recentActivity: "Tournament qualifier round completed",
    memberList: [
      { name: "Alex Chen", role: "Captain", avatar: "AC" },
      { name: "Jordan Rivera", role: "Member", avatar: "JR" },
      { name: "Lisa Chen", role: "Member", avatar: "LC" },
    ],
  },
  {
    id: "3",
    name: "Run NYC Marathon",
    sport: "Running",
    members: 20,
    maxMembers: 25,
    avatar: "RM",
    description: "Training group for marathon and half-marathon runners",
    upcomingEvents: 4,
    wins: 0,
    losses: 0,
    captain: "Emily Park",
    captainAvatar: "EP",
    recentActivity: "Group PR set at Central Park 10K",
    memberList: [
      { name: "Emily Park", role: "Captain", avatar: "EP" },
      { name: "Carlos Rivera", role: "Co-Captain", avatar: "CR" },
      { name: "Jordan Rivera", role: "Member", avatar: "JR" },
    ],
  },
]

export const athletes = [
  { id: "1", name: "Sarah Lee", sport: "Volleyball", ranking: "#12 NYC", followers: 890, engagement: 8.2, avatar: "SL", status: "active", collaborations: 3 },
  { id: "2", name: "Carlos Rivera", sport: "Soccer", ranking: "#5 NYC", followers: 3400, engagement: 12.5, avatar: "CR", status: "active", collaborations: 5 },
  { id: "3", name: "Mike Johnson", sport: "Basketball", ranking: "#3 NYC", followers: 1250, engagement: 9.8, avatar: "MJ", status: "active", collaborations: 7 },
  { id: "4", name: "Emily Park", sport: "Swimming", ranking: "#1 NYC", followers: 5600, engagement: 15.3, avatar: "EP", status: "pending", collaborations: 2 },
  { id: "5", name: "James Wright", sport: "Boxing", ranking: "#8 NYC", followers: 780, engagement: 6.4, avatar: "JW", status: "inactive", collaborations: 1 },
]

export const businessDashboardData = {
  totalRevenue: 24580,
  totalBookings: 342,
  totalCustomers: 1289,
  activeActivities: 12,
  revenueChange: 12.5,
  bookingChange: 8.3,
  customerChange: 15.2,
  monthlyRevenue: [
    { month: "Sep", revenue: 3200 },
    { month: "Oct", revenue: 3800 },
    { month: "Nov", revenue: 4100 },
    { month: "Dec", revenue: 3600 },
    { month: "Jan", revenue: 4800 },
    { month: "Feb", revenue: 5080 },
  ],
  topActivities: [
    { name: "Basketball League", bookings: 89, revenue: 4450 },
    { name: "Tennis Coaching", bookings: 67, revenue: 5025 },
    { name: "Swimming Laps", bookings: 54, revenue: 1890 },
    { name: "Yoga Class", bookings: 48, revenue: 1200 },
  ],
  recentBookings: [
    { id: "B001", customer: "Jordan Rivera", activity: "Basketball League", date: "Feb 7, 2026", amount: 15, status: "confirmed" },
    { id: "B002", customer: "Emily Park", activity: "Swimming Laps", date: "Feb 7, 2026", amount: 20, status: "confirmed" },
    { id: "B003", customer: "David Kim", activity: "Tennis Coaching", date: "Feb 6, 2026", amount: 75, status: "pending" },
    { id: "B004", customer: "Lisa Chen", activity: "Yoga Class", date: "Feb 6, 2026", amount: 25, status: "confirmed" },
    { id: "B005", customer: "Mark Brown", activity: "Basketball League", date: "Feb 5, 2026", amount: 15, status: "cancelled" },
  ],
  teamMembers: [
    { name: "Mike Johnson", role: "Head Coach", avatar: "MJ", status: "active" },
    { name: "Sarah Lee", role: "Trainer", avatar: "SL", status: "active" },
    { name: "Alex Chen", role: "Manager", avatar: "AC", status: "active" },
    { name: "Emily Park", role: "Instructor", avatar: "EP", status: "on-leave" },
  ],
}

export const communityPeople = [
  {
    id: "cp-1",
    name: "Sarah Mitchell",
    avatar: "SM",
    location: "New York, NY",
    sports: ["Running", "Yoga", "Cycling"],
    level: "Advanced",
    activities: 156,
    squads: 3,
    bio: "Marathon runner and yoga instructor. Love connecting with fitness enthusiasts!",
    isConnected: true,
    mutualConnections: 12,
  },
  {
    id: "cp-2",
    name: "Mike Chen",
    avatar: "MC",
    location: "Brooklyn, NY",
    sports: ["Basketball", "Swimming", "Tennis"],
    level: "Intermediate",
    activities: 89,
    squads: 2,
    bio: "Basketball enthusiast and weekend warrior. Always up for a challenge!",
    isConnected: false,
    mutualConnections: 8,
  },
  {
    id: "cp-3",
    name: "Emily Rodriguez",
    avatar: "ER",
    location: "Manhattan, NY",
    sports: ["Yoga", "Pilates"],
    level: "Expert",
    activities: 234,
    squads: 4,
    bio: "Certified yoga instructor with 10+ years of experience.",
    isConnected: true,
    mutualConnections: 15,
  },
  {
    id: "cp-4",
    name: "James Park",
    avatar: "JP",
    location: "Queens, NY",
    sports: ["CrossFit", "Running", "Boxing"],
    level: "Advanced",
    activities: 178,
    squads: 3,
    bio: "CrossFit coach and personal trainer. Pushing limits every day!",
    isConnected: false,
    mutualConnections: 5,
  },
  {
    id: "cp-5",
    name: "Lisa Anderson",
    avatar: "LA",
    location: "Brooklyn, NY",
    sports: ["Swimming", "Cycling"],
    level: "Advanced",
    activities: 201,
    squads: 5,
    bio: "Triathlete and endurance athlete. Training for Ironman 2026!",
    isConnected: false,
    mutualConnections: 10,
  },
  {
    id: "cp-6",
    name: "David Kim",
    avatar: "DK",
    location: "Manhattan, NY",
    sports: ["Tennis", "Badminton"],
    level: "Intermediate",
    activities: 92,
    squads: 2,
    bio: "Racket sports enthusiast. Looking for tennis partners!",
    isConnected: true,
    mutualConnections: 7,
  },
  {
    id: "cp-7",
    name: "Amanda Foster",
    avatar: "AF",
    location: "Upper West Side, NY",
    sports: ["Dancing", "Zumba", "Yoga"],
    level: "Intermediate",
    activities: 145,
    squads: 3,
    bio: "Dance fitness instructor spreading joy through movement!",
    isConnected: false,
    mutualConnections: 9,
  },
  {
    id: "cp-8",
    name: "Marcus Johnson",
    avatar: "MJ",
    location: "Bronx, NY",
    sports: ["Soccer", "Football", "Running"],
    level: "Advanced",
    activities: 167,
    squads: 4,
    bio: "Soccer coach and fitness enthusiast. Team player at heart!",
    isConnected: false,
    mutualConnections: 11,
  },
]

export const communityGroups = [
  {
    id: "cg-1",
    name: "NYC Fitness Community",
    sport: "Multi-Sport",
    members: 156,
    description: "General fitness group for all sports and activities in NYC.",
    activityLevel: "High",
    isJoined: true,
  },
  {
    id: "cg-2",
    name: "Weekend Warriors Basketball",
    sport: "Basketball",
    members: 48,
    description: "Casual basketball games every Saturday and Sunday.",
    activityLevel: "Moderate",
    isJoined: false,
  },
  {
    id: "cg-3",
    name: "Manhattan Yoga Circle",
    sport: "Yoga",
    members: 92,
    description: "Outdoor yoga sessions in Central Park and rooftop studios.",
    activityLevel: "High",
    isJoined: true,
  },
  {
    id: "cg-4",
    name: "Brooklyn Runners United",
    sport: "Running",
    members: 210,
    description: "Running club for all levels. Weekly group runs and races.",
    activityLevel: "Very High",
    isJoined: false,
  },
  {
    id: "cg-5",
    name: "NYC Tennis Network",
    sport: "Tennis",
    members: 67,
    description: "Connect with tennis players for matches and coaching.",
    activityLevel: "Moderate",
    isJoined: false,
  },
  {
    id: "cg-6",
    name: "CrossFit NYC Crew",
    sport: "CrossFit",
    members: 35,
    description: "High-intensity training group for CrossFit enthusiasts.",
    activityLevel: "Very High",
    isJoined: false,
  },
]

// ==================== Profile Enhanced Data ====================

export const achievements = [
  { id: "1", title: "Early Bird", description: "Joined 10 morning activities", icon: "Trophy", date: "Jan 15, 2026", color: "text-yellow-500" },
  { id: "2", title: "Social Butterfly", description: "Connected with 50+ people", icon: "Users", date: "Jan 20, 2026", color: "text-pink-500" },
  { id: "3", title: "Fitness Streak", description: "30-day activity streak", icon: "Target", date: "Feb 1, 2026", color: "text-green-500" },
  { id: "4", title: "Multi-Sport Athlete", description: "Tried 5 different sports", icon: "Award", date: "Jan 25, 2026", color: "text-blue-500" },
]

export const activityHistory = [
  { id: "1", title: "Morning Yoga Flow", sport: "Yoga", date: "Feb 10, 2026", status: "upcoming" as const },
  { id: "2", title: "Basketball Pickup Game", sport: "Basketball", date: "Feb 8, 2026", status: "completed" as const },
  { id: "3", title: "HIIT Training Session", sport: "Fitness", date: "Feb 6, 2026", status: "completed" as const },
  { id: "4", title: "Weekend Soccer Match", sport: "Soccer", date: "Feb 5, 2026", status: "completed" as const },
  { id: "5", title: "Swimming Drills", sport: "Swimming", date: "Feb 3, 2026", status: "completed" as const },
]

export const progressData = [
  { date: "Jan 25", value: 185 },
  { date: "Jan 27", value: 184 },
  { date: "Jan 29", value: 183 },
  { date: "Jan 31", value: 181 },
  { date: "Feb 2", value: 180 },
  { date: "Feb 5", value: 179 },
  { date: "Feb 8", value: 178 },
]

export const personalProfile = {
  height: "5'10\"",
  currentWeight: "178 lbs",
  targetWeight: "170 lbs",
  bmi: 25.5,
  bodyFat: "18%",
}

export const recommendedActivities = [
  { id: "ra-1", title: "Morning HIIT Blast", sport: "Fitness", date: "Feb 12, 2026", time: "7:00 AM", location: "Chelsea Piers Gym", spots: 4 },
  { id: "ra-2", title: "5K Recovery Run", sport: "Running", date: "Feb 13, 2026", time: "6:30 AM", location: "Central Park, NYC", spots: 12 },
  { id: "ra-3", title: "Yoga for Athletes", sport: "Yoga", date: "Feb 14, 2026", time: "8:00 AM", location: "Brooklyn Yoga Studio", spots: 6 },
]

// ==================== Marketplace Stores ====================

export const marketplaceStores = [
  { id: "decathlon", name: "Decathlon", logo: "🏃", description: "Sports equipment for all", productCount: 245, rating: 4.6 },
  { id: "nike", name: "Nike", logo: "✓", description: "Just Do It", productCount: 189, rating: 4.8 },
  { id: "adidas", name: "Adidas", logo: "⚡", description: "Impossible is Nothing", productCount: 203, rating: 4.7 },
  { id: "underarmour", name: "Under Armour", logo: "🎯", description: "Performance gear", productCount: 156, rating: 4.5 },
]
