export type PageRoute =
  | "home"
  | "explore"
  | "activities"
  | "activity-detail"
  | "facilities"
  | "facility-detail"
  | "marketplace"
  | "product-detail"
  | "services"
  | "service-detail"
  | "businesses"
  | "business-detail"
  | "jobs"
  | "messages"
  | "conversation"
  | "notifications"
  | "profile"
  | "settings"
  | "settings-profile"
  | "settings-privacy"
  | "settings-notifications"
  | "settings-payment"
  | "settings-wallet"
  | "settings-language"
  | "settings-blocked"
  | "settings-terms"
  | "settings-privacy-policy"
  | "settings-help"
  | "business-dashboard"
  | "business-activities"
  | "business-customers"
  | "business-team"
  | "business-analytics"
  | "business-campaigns"
  | "business-resources"
  | "business-partners"
  | "signin"
  | "signup"
  | "forgot-password"
  | "reset-password"
  | "verify-email"
  | "choose-sports"
  | "set-goals"
  | "onboarding-confirmation"

export interface NavigationState {
  currentPage: PageRoute
  detailId: string | null
  isBusinessMode: boolean
}
